################################# Default configuration ###################
baseURL = "https://panarchic.ch/"
title = "PANARCHIC Project"
# theme = "meghna-hugo"
themesDir = "themes"
# post pagination
paginate = "1"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"]

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
pre = "#"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "Our team"
pre = "#"
url = "team"
weight = 2

[[Languages.en.menu.main]]
name = "Our Partners"
pre = "#"
url = "portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Our Publications"
pre = "#"
url = "pricing"
weight = 4

[[Languages.en.menu.main]]
name = "Our Packages"
pre = "#"
url = "testimonial"
weight = 5

# [[Languages.en.menu.main]]
# name = "team"
# pre = "#"
# url = "team"
# weight = 4
#
# [[Languages.en.menu.main]]
# name = "pricing"
# pre = "#"
# url = "pricing"
# weight = 5
#
# [[Languages.en.menu.main]]
# name = "blog"
# pre = "#"
# url = "blog"
# weight = 6
#
# [[Languages.en.menu.main]]
# name = "contact"
# pre = "#"
# url = "contact"
# weight = 7
#
# [[Languages.en.menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8


################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "A propos"
pre = "#"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Notre Equipe"
pre = "#"
url = "services"
weight = 2

[[Languages.fr.menu.main]]
name = "Nos Partenaires"
pre = "#"
url = "portfolio"
weight = 3

[[Languages.fr.menu.main]]
name = "Nos Publications"
pre = "#"
url = "pricing"
weight = 4

[[Languages.fr.menu.main]]
name = "Nos Packages"
pre = "#"
url = "testimonial"
weight = 5

# [[Languages.fr.menu.main]]
# name = "Ã©quipe"
# pre = "#"
# url = "team"
# weight = 4
#
# [[Languages.fr.menu.main]]
# name = "tarification"
# pre = "#"
# url = "pricing"
# weight = 5
#
# [[Languages.fr.menu.main]]
# name = "blog"
# pre = "#"
# url = "blog"
# weight = 6
#
# [[Languages.fr.menu.main]]
# name = "contact"
# pre = "#"
# url = "contact"
# weight = 7
#
# [[Languages.fr.menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/panarchic.svg"
# Meta data
description = "Panarchic Project Website"
author = "Panarchic"
# # Google Analytics
# google_analytics_id = "" # Your ID
# # post share
# post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "46.221502309431955"
map_longitude = "6.143557339681708"
map_marker = "images/marker.png"

############################# social icons ##########################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# link = "#"
#
# [[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# link = "#"
#
# [[params.social]]
# icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
# link = "#"
#
# [[params.social]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# link = "#"
#
# [[params.social]]
# icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
# link = "#"
#
# [[params.social]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Made with the help of Hugo and Meghna"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "Made with the help of Hugo and Meghna"
